-- Thin SkillV2 authoring: definitions and SourceHelper relations only.
-- Design reference: FreeKill skill_skeleton.lua addEffect/createSkill;
-- independent implementation against this engine's existing V2 factories.
local M = {}
local Assembly = {}
Assembly.__index = Assembly

local factories = {
    trigger = "CreateTriggerSkillV2",
    active = "CreateViewAsSkillV2",
    viewas = "CreateViewAsSkillV2",
    distance = "CreateDistanceSkillV2",
    maxcards = "CreateMaxCardsSkillV2",
    targetmod = "CreateTargetModSkillV2",
    atkrange = "CreateAttackRangeSkillV2",
}

local function copy(value, seen)
    if type(value) ~= "table" then return value end
    seen = seen or {}
    assert(not seen[value], "skill assembly specs must not contain cyclic tables")
    seen[value] = true
    local result = {}
    for key, item in pairs(value) do result[key] = copy(item, seen) end
    seen[value] = nil
    return result
end

local function validName(name)
    return type(name) == "string" and name:match("^[%w_]+$") ~= nil
end

local function isActive(kind)
    return kind == "active" or kind == "viewas"
end

function M.new(spec)
    assert(type(spec) == "table" and validName(spec.name),
        "skill assembly requires an ASCII alphanumeric/underscore name")
    local self = setmetatable({name = spec.name, _effects = {}, _ids = {}}, Assembly)
    for key in pairs(spec) do
        assert(key == "name" or key == "effects", "unknown assembly field: " .. tostring(key))
    end
    if spec.effects ~= nil then
        assert(type(spec.effects) == "table", "effects must be a dense array")
        local count = 0
        for key in pairs(spec.effects) do
            assert(type(key) == "number" and key >= 1 and key % 1 == 0,
                "effects must be a dense array")
            count = count + 1
        end
        for i = 1, count do
            local effect = spec.effects[i]
            assert(type(effect) == "table", "effects must be a dense array")
            self:addEffect(effect.kind, effect)
        end
    end
    return self
end

function Assembly:addEffect(kind, spec)
    assert(not self._skills, "cannot add effects after createSkill")
    assert(factories[kind], "unsupported SkillV2 effect kind: " .. tostring(kind))
    assert(type(spec) == "table" and validName(spec.id), "each effect requires a stable id")
    assert(not self._ids[spec.id], "duplicate effect id: " .. spec.id)
    assert(spec.name == nil, "effect names are generated by the assembly")
    assert(spec.kind == nil or spec.kind == kind, "effect kind disagrees with addEffect")
    assert(spec.global ~= true and spec.scenario == nil and spec.rule == nil,
        "assembly effects must use player skill instances")
    assert(spec.holder_selector == nil or spec.holder_selector ~= sgs.CorrectSkill_System,
        "assembly corrections must use player skill instances")
    assert(spec.target_tip == nil or type(spec.target_tip) == "table",
        "target_tip must be declarative data, not a callback")
    assert(spec.view_as_skill == nil, "use one active/viewas effect instead of view_as_skill")
    if isActive(kind) then
        assert(not self._active, "an assembly permits only one active/viewas effect")
        self._active = spec.id
    end
    local effect = copy(spec)
    effect.kind = kind
    self._effects[#self._effects + 1] = effect
    self._ids[effect.id] = effect
    return self
end

-- Active controls the visible button. Otherwise the first trigger is the root,
-- or the first correction for a correction-only assembly. Explicit ids keep
-- helper names stable when effects are reordered.
function Assembly:createSkill()
    if self._skills then return self._main end
    assert(#self._effects > 0, "skill assembly needs at least one effect")
    local root = self._active and self._ids[self._active] or nil
    if not root then
        for _, effect in ipairs(self._effects) do
            if effect.kind == "trigger" then root = effect; break end
        end
    end
    root = root or self._effects[1]
    local ordered = {root}
    for _, effect in ipairs(self._effects) do
        if effect ~= root then ordered[#ordered + 1] = effect end
        assert(type(sgs[factories[effect.kind]]) == "function", "missing V2 factory: " .. factories[effect.kind])
    end
    local skills, names = {}, {}
    for _, effect in ipairs(ordered) do
        local spec = copy(effect)
        spec.id, spec.kind = nil, nil
        spec.name = effect == root and self.name or ("#" .. self.name .. "__" .. effect.id)
        skills[#skills + 1] = sgs[factories[effect.kind]](spec)
        names[effect.id] = spec.name
    end
    self._skills, self._names, self._main = skills, names, skills[1]
    return self._main
end

-- Register before the package is returned to the engine, like ordinary
-- insertRelatedSkills calls. General uses the registered name, avoiding a
-- second owner of the same definition. Repeating with this package is safe.
function Assembly:register(extension, general)
    assert(extension ~= nil, "register requires a package")
    self:createSkill()
    if self._package then
        assert(self._package == extension, "assembly already registered to another package")
    else
        for _, skill in ipairs(self._skills) do
            assert(not sgs.Sanguosha:getSkill(skill:objectName()),
                "skill assembly name already registered: " .. skill:objectName())
        end
        local skills = sgs.SkillList()
        for _, skill in ipairs(self._skills) do skills:append(skill) end
        sgs.Sanguosha:addSkills(skills)
        for i = 2, #self._skills do
            extension:insertRelatedSkills(self.name, self._skills[i]:objectName())
        end
        self._package = extension
    end
    if general then
        self._generals = self._generals or {}
        if not self._generals[general] then
            general:addSkill(self.name)
            self._generals[general] = true
        end
    end
    return self._main
end

function Assembly:effectName(id)
    assert(self._ids[id], "unknown effect id: " .. tostring(id))
    self:createSkill()
    return self._names[id]
end

-- Resolve only this live root's own direct SourceHelper. Never choose another
-- same-name instance, attached grant, sibling, descendant, or source owner.
-- IDs are local to owner; retain the owner name in the returned value ref.
function Assembly:effectRef(owner, rootInstanceID, id)
    local name = self:effectName(id)
    if not owner or type(rootInstanceID) ~= "number" or rootInstanceID <= 0
        or rootInstanceID % 1 ~= 0 or not owner:hasSkillInstance(self.name, rootInstanceID) then
        return nil
    end
    if name == self.name then
        return sgs.SkillInstanceRef(owner:objectName(), sgs.SkillInstanceKey(name, rootInstanceID))
    end
    local parent = sgs.SkillInstanceKey(self.name, rootInstanceID)
    local found
    for _, child in sgs.qlist(owner:getChildSkillInstanceKeys(parent)) do
        if child.skillName == name then
            -- Ambiguous corrupted relationships must not silently buff one.
            if found then return nil end
            found = sgs.SkillInstanceRef(owner:objectName(), child)
        end
    end
    return found
end

function M.create(spec)
    local assembly = M.new(spec)
    assembly:createSkill()
    return assembly
end

return M
