#!/usr/bin/env python3
"""E2E: extensions mount QML elements on the table (Engine:addQmlMark, Room:addQmlElement).

Flow
----
    1. Build a probe asset tree like ui_theme_runtime_smoke.py: the repository is
       symlinked, lua/config.lua declares extensions/qmltableprobe.lua, and
       qmlprobe/ holds the probe QML files.
    2. The probe extension binds "@qmlprobe_*" marks to qmlprobe/Mark.qml and, on
       the first turn, adds a broadcast board, a board for the human seat only, a
       board that follows another seat, one element whose file is missing, and one
       request outside the game folder that the server must refuse. On the second
       turn it updates the board, removes the human's board and clears the mark.
    3. Run gui_network_smoke.py once landscape (1280x720) and once portrait
       (540x960, responsive layout) and gate on the client's "qml_elements:<n>" stages.

Usage:
    python3 tools/autotest/qml_table_layer_smoke.py --exe-root . \\
        --server-exe debug/qsanguosha_server --client-exe debug/QSanguosha \\
        --artifact-dir artifacts/qml-table-layer --seed 20261007 --no-xvfb --platform xcb
"""

import argparse
import json
import os
import shutil
import subprocess
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
STAGE_MARKER = "NETWORK_UI_STAGE"
PROBE_SCRIPT = "extensions/qmltableprobe.lua"

PROBE_LUA = r'''
-- E2E probe for table QML elements; generated by tools/autotest/qml_table_layer_smoke.py.
local extension = sgs.Package("qmltableprobe", sgs.Package_GeneralPack)

sgs.Sanguosha:addQmlMark("@qmlprobe_*", "qmlprobe/Mark.qml", "avatar")

local function humanSeat(room)
	for _, p in sgs.qlist(room:getPlayers()) do
		if p:getState() == "online" then return p end
	end
	return nil
end

local function otherSeat(room, human)
	for _, p in sgs.qlist(room:getPlayers()) do
		if p ~= human then return p end
	end
	return nil
end

local probe = sgs.CreateTriggerSkill {
	name = "#qmltableprobe",
	global = true,
	priority = 20,
	frequency = sgs.Skill_Compulsory,
	events = { sgs.TurnStart },
	can_trigger = function(self, target)
		return target ~= nil
	end,
	on_trigger = function(self, event, player, data)
		local room = player:getRoom()
		local step = room:getTag("QmlTableProbeStep"):toInt() + 1
		room:setTag("QmlTableProbeStep", sgs.QVariant(step))
		local human = humanSeat(room)
		if step == 1 then
			room:addQmlElement("board", "qmlprobe/Board.qml", "table-center", { round = 1, names = { "a", "b" } })
			if human then
				room:setPlayerMark(human, "@qmlprobe_star", 2)
				room:addQmlElement("mine", "qmlprobe/Board.qml", "screen-top", { round = 0 }, human)
				local other = otherSeat(room, human)
				if other then
					room:addQmlElement("follow", "qmlprobe/Board.qml", "seat:" .. other:objectName(), { round = 9 })
				end
			end
			room:addQmlElement("nofile", "qmlprobe/Missing.qml", "screen-bottom", {})
			-- Outside the game folder: the server must refuse it and the client never sees it.
			room:addQmlElement("outside", "../qmlprobe-outside.qml", "table-center", {})
		elseif step == 2 then
			room:updateQmlElement("board", { round = 2 })
			if human then
				room:removeQmlElement("mine", human)
				room:setPlayerMark(human, "@qmlprobe_star", 0)
			end
		end
		return false
	end,
}

local skills = sgs.SkillList()
if not sgs.Sanguosha:getSkill("#qmltableprobe") then skills:append(probe) end
sgs.Sanguosha:addSkills(skills)

return { extension }
'''

MARK_QML = '''import QtQuick
Rectangle {
    property var qs
    implicitWidth: 24
    implicitHeight: 24
    radius: 12
    color: "gold"
    Text { anchors.centerIn: parent; text: qs && qs.data ? qs.data.value : "" }
}
'''

BOARD_QML = '''import QtQuick
Rectangle {
    property var qs
    property bool qsInteractive: true
    property int clicks: 0
    implicitWidth: 160
    implicitHeight: 40
    color: "#c0000000"
    Text {
        anchors.centerIn: parent
        color: "white"
        text: "round " + (qs && qs.data ? qs.data.round : "?")
    }
    TapHandler { onTapped: parent.clicks += 1 }
}
'''

RUNS = [("landscape", "1280x720"), ("portrait", "540x960")]


def symlink_farm(source, target, skip=()):
    os.makedirs(target, exist_ok=True)
    for name in os.listdir(source):
        if name in skip:
            continue
        os.symlink(os.path.join(source, name), os.path.join(target, name))


def build_probe_tree(repo, tree):
    if os.path.lexists(tree):
        shutil.rmtree(tree)
    symlink_farm(repo, tree, skip={"lua", "extensions", "packages", ".git", "build", "builds", "artifacts"})
    # The package catalog refuses a symlinked packages/ directory.
    if os.path.isdir(os.path.join(repo, "packages")):
        shutil.copytree(os.path.join(repo, "packages"), os.path.join(tree, "packages"), symlinks=True)
    symlink_farm(os.path.join(repo, "lua"), os.path.join(tree, "lua"), skip={"config.lua"})
    symlink_farm(os.path.join(repo, "extensions"), os.path.join(tree, "extensions"))

    with open(os.path.join(repo, "lua", "config.lua"), encoding="utf-8") as f:
        config = f.read()
    start = config.index("extension_names = {")
    end = config.index("\n\t},", start)
    body = config[start:end].rstrip()
    if not body.endswith(","):
        body += ","
    config = config[:start] + body + '\n\t\t"%s",' % PROBE_SCRIPT + config[end:]
    with open(os.path.join(tree, "lua", "config.lua"), "w", encoding="utf-8") as f:
        f.write(config)
    with open(os.path.join(tree, PROBE_SCRIPT), "w", encoding="utf-8") as f:
        f.write(PROBE_LUA)
    probe_dir = os.path.join(tree, "qmlprobe")
    os.makedirs(probe_dir)
    for name, text in (("Mark.qml", MARK_QML), ("Board.qml", BOARD_QML)):
        with open(os.path.join(probe_dir, name), "w", encoding="utf-8") as f:
            f.write(text)


def read_stages(client_log):
    stages = []
    with open(client_log, encoding="utf-8", errors="replace") as f:
        for line in f:
            at = line.find(STAGE_MARKER)
            if at < 0:
                continue
            try:
                stages.append(json.loads(line[at + len(STAGE_MARKER):].strip()))
            except ValueError:
                pass
    return [s for s in stages if str(s.get("stage", "")).startswith("qml_elements:")]


def center(rect):
    return (rect["x"] + rect["w"] / 2.0, rect["y"] + rect["h"] / 2.0)


def inside(point, rect, slack=2.0):
    return (rect["x"] - slack <= point[0] <= rect["x"] + rect["w"] + slack
            and rect["y"] - slack <= point[1] <= rect["y"] + rect["h"] + slack)


def intersects(a, b):
    return not (a["x"] + a["w"] <= b["x"] or b["x"] + b["w"] <= a["x"]
                or a["y"] + a["h"] <= b["y"] or b["y"] + b["h"] <= a["y"])


def evaluate(stages, orientation):
    problems = []
    if not stages:
        return ["the client never reported a qml_elements stage"]
    seen = {}
    for stage in stages:
        for element in stage.get("elements", []):
            seen.setdefault(element["key"], []).append((stage, element))

    def last(key):
        return seen[key][-1] if key in seen else (None, None)

    for key in seen:
        if "outside" in key:
            problems.append("an element outside the game folder reached the client: %s" % key)

    # Broadcast board: shown at the table center, then updated in place.
    stage, board = last("all/board")
    if board is None:
        problems.append("all/board never appeared")
    else:
        rounds = [e.get("data", {}).get("round") for _, e in seen["all/board"]]
        if 2 not in rounds:
            problems.append("all/board never showed round 2 after updateQmlElement: %r" % rounds)
        if len({e.get("instance") for _, e in seen["all/board"] if e.get("instance")}) != 1:
            problems.append("all/board was recreated instead of updated in place")
        if board.get("error"):
            problems.append("all/board failed to load: %s" % board["error"])
        if not board.get("visible"):
            problems.append("all/board is not visible")
        elif not inside(center(board["rect"]), {"x": stage["table_center"]["x"] - 2,
                                                "y": stage["table_center"]["y"] - 2, "w": 4, "h": 4}):
            problems.append("all/board center %r is not at the table center %r"
                            % (center(board["rect"]), stage["table_center"]))

    # Targeted board: appears for the human, then removed.
    if "player/mine" not in seen:
        problems.append("player/mine never appeared")
    elif any(e["key"] == "player/mine" for e in stages[-1].get("elements", [])):
        problems.append("player/mine is still shown after removeQmlElement")
    else:
        _, mine = seen["player/mine"][-1]
        header = stages[-1].get("header_rect")
        if header and mine.get("visible") and intersects(mine["rect"], header):
            problems.append("player/mine overlaps the header")

    # Seat-following board: centered inside its seat.
    _, follow = last("all/follow")
    if follow is None:
        problems.append("all/follow never appeared")
    elif follow.get("visible") and not inside(center(follow["rect"]), follow["seat_rect"]):
        problems.append("all/follow center %r is outside its seat %r" % (center(follow["rect"]), follow["seat_rect"]))

    # Missing file: reported, never created, game continues.
    _, missing = last("all/nofile")
    if missing is None:
        problems.append("all/nofile never reached the layer")
    elif not missing.get("error") or missing.get("instance"):
        problems.append("all/nofile should carry an error and no item: %r" % missing)

    # Mark binding on the human's own seat (dashboard avatar area).
    mark_keys = [k for k in seen if k.startswith("mark/") and k.endswith("/@qmlprobe_star")]
    if not mark_keys:
        problems.append("the @qmlprobe_star mark never became a QML element")
    else:
        _, mark = seen[mark_keys[0]][0]
        if mark.get("data", {}).get("value") != 2:
            problems.append("mark element data is %r, expected value 2" % mark.get("data"))
        if mark.get("visible") and not inside(center(mark["rect"]), mark["seat_rect"]):
            problems.append("mark element center %r is outside the avatar area %r"
                            % (center(mark["rect"]), mark["seat_rect"]))
        if any(e["key"] == mark_keys[0] for e in stages[-1].get("elements", [])):
            problems.append("the mark element is still shown after the mark dropped to 0")

    # Table and screen elements never cover the hand / dashboard area.
    for stage in stages:
        interaction = stage.get("interaction_rect")
        for element in stage.get("elements", []):
            if element.get("player") or not element.get("visible") or not interaction:
                continue
            if element["anchor"] in ("table-center", "screen-top") and intersects(element["rect"], interaction):
                problems.append("%s overlaps the dashboard area in %s" % (element["key"], stage["stage"]))

    if orientation == "portrait":
        profiles = {s.get("profile") for s in stages}
        if "portrait" not in profiles:
            problems.append("portrait run never reported profile=portrait: %r" % profiles)
    return problems


def run_once(args, repo, tree, artifacts, orientation, window):
    label = "qml-table-%s-%s-%s" % (orientation, args.mode, args.seed)
    command = [sys.executable, os.path.join(HERE, "gui_network_smoke.py"),
               "--exe-root", repo, "--workdir", tree,
               "--mode", args.mode, "--seed", args.seed,
               "--artifact-dir", artifacts, "--label", label,
               "--platform", args.platform, "--process-timeout", args.process_timeout,
               "--client-window", window,
               "--known-base-defect", "server-teardown-crash"]
    if args.no_xvfb:
        command.append("--no-xvfb")
    for flag, value in (("--server-exe", args.server_exe), ("--client-exe", args.client_exe)):
        if value:
            command += [flag, os.path.abspath(value)]
    env = dict(os.environ, QSAN_ASSET_ROOT=tree)
    smoke = subprocess.run(command, env=env)
    client_log = os.path.join(artifacts, "network-ui-smoke-%s-client.log" % label)
    problems = []
    stages = []
    if smoke.returncode != 0:
        problems.append("gui_network_smoke.py exited %d" % smoke.returncode)
    if not os.path.isfile(client_log):
        problems.append("no client log at %s" % client_log)
    else:
        stages = read_stages(client_log)
        problems += evaluate(stages, orientation)
    return label, stages, problems


def main():
    parser = argparse.ArgumentParser(description=__doc__,
                                     formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument("--exe-root", default=".")
    parser.add_argument("--server-exe")
    parser.add_argument("--client-exe")
    parser.add_argument("--artifact-dir", default="artifacts/qml-table-layer")
    parser.add_argument("--mode", default="02p")
    parser.add_argument("--seed", default="20261007")
    parser.add_argument("--platform", default="xcb")
    parser.add_argument("--no-xvfb", action="store_true")
    parser.add_argument("--process-timeout", default="900")
    parser.add_argument("--orientation", choices=("landscape", "portrait", "both"), default="both")
    args = parser.parse_args()

    repo = os.path.abspath(args.exe_root)
    artifacts = os.path.abspath(args.artifact_dir)
    os.makedirs(artifacts, exist_ok=True)
    tree = os.path.join(artifacts, "probe-tree")
    build_probe_tree(repo, tree)

    summary = {"mode": args.mode, "seed": args.seed, "runs": []}
    failed = False
    for orientation, window in RUNS:
        if args.orientation not in ("both", orientation):
            continue
        label, stages, problems = run_once(args, repo, tree, artifacts, orientation, window)
        failed = failed or bool(problems)
        summary["runs"].append({"orientation": orientation, "window": window, "label": label,
                                "stages": len(stages), "ok": not problems, "problems": problems})
        print("\n[%s] qml_elements stages: %d" % (orientation, len(stages)))
        for problem in problems:
            print("  - %s" % problem, file=sys.stderr)
    summary["ok"] = not failed
    with open(os.path.join(artifacts, "qml-table-layer-summary.json"), "w", encoding="utf-8") as f:
        json.dump(summary, f, ensure_ascii=False, indent=2)
    print("QML table layer smoke %s" % ("FAILED" if failed else "PASSED"))
    return 1 if failed else 0


if __name__ == "__main__":
    sys.exit(main())
