#!/usr/bin/env python3
"""E2E: a running room changes theme slots and colors mid-game (Room::setUiElement).

Flow
----
    1. Build a probe asset tree: every top-level entry of the repository is
       symlinked, except lua/ and extensions/, which are rebuilt as symlink
       farms so that lua/config.lua can declare one extra extension and
       extensions/uithemeprobe.lua can be added. The repository is not touched.
    2. The probe extension adds a global trigger skill. On the first turn it
       calls room:setUiSlot / setUiColor / setUiThemePack (broadcast and one
       targeted at the human seat) plus one request the client must reject;
       on the second turn it clears table-bg and drops the pack again.
    3. Run tools/autotest/gui_network_smoke.py with QSAN_ASSET_ROOT pointing at
       the probe tree, so the real server and the real GUI client both load it.
    4. Gate on the client's "ui_theme_changed:<n>" stages: every expected change
       arrives in order, resolves to the probe's file, the rejected request never
       shows up, and the game still finishes cleanly. Screenshots taken after
       each change are kept as evidence.

Usage:
    python3 tools/autotest/ui_theme_runtime_smoke.py --exe-root . \\
        --server-exe debug/qsanguosha_server --client-exe debug/QSanguosha \\
        --artifact-dir artifacts/ui-theme-runtime --seed 20261007 --no-xvfb --platform xcb
"""

import argparse
import json
import os
import shutil
import subprocess
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
STAGE_MARKER = "NETWORK_UI_STAGE"
PROBE_SCRIPT = "extensions/uithemeprobe.lua"

PROBE_LUA = r'''
-- E2E probe for Room::setUiElement; generated by tools/autotest/ui_theme_runtime_smoke.py.
local extension = sgs.Package("uithemeprobe", sgs.Package_GeneralPack)

local function humanSeat(room)
	for _, p in sgs.qlist(room:getPlayers()) do
		if p:getState() == "online" then return p end
	end
	return nil
end

local probe = sgs.CreateTriggerSkill {
	name = "#uithemeprobe",
	global = true,
	priority = 20,
	frequency = sgs.Skill_Compulsory,
	events = { sgs.TurnStart },
	can_trigger = function(self, target)
		return target ~= nil
	end,
	on_trigger = function(self, event, player, data)
		local room = player:getRoom()
		local step = room:getTag("UiThemeProbeStep"):toInt() + 1
		room:setTag("UiThemeProbeStep", sgs.QVariant(step))
		if step == 1 then
			room:setUiSlot("table-bg", "image/system/backdrop/wei.jpg")
			room:setUiSlot("card-back", "themes/demo-crimson/card-back.png")
			room:setUiSlot("magatamas", "uithemeprobe-art/magatamas/")
			room:setUiColor("log-text", "#ffd700")
			room:setUiThemePack("demo-jade")
			-- Escapes the asset root: every client must refuse it.
			room:setUiSlot("photo-frame", "../uithemeprobe-outside.png")
			local human = humanSeat(room)
			if human then room:setUiColor("table-text", "#00ff00", human) end
		elseif step == 2 then
			room:setUiSlot("table-bg", "")
			room:setUiThemePack("demo-jade", false)
		end
		return false
	end,
}

local skills = sgs.SkillList()
if not sgs.Sanguosha:getSkill("#uithemeprobe") then skills:append(probe) end
sgs.Sanguosha:addSkills(skills)

return { extension }
'''

# (kind, id, resolved check) in the order the client must report them.
EXPECTED = [
    ("slot", "table-bg", lambda r, t: r.endswith("image/system/backdrop/wei.jpg")),
    ("slot", "card-back", lambda r, t: r.endswith("themes/demo-crimson/card-back.png")),
    ("slot", "magatamas", lambda r, t: r.rstrip("/").endswith("uithemeprobe-art/magatamas")),
    ("color", "log-text", lambda r, t: r.lower() == "#ffd700"),
    ("pack", "demo-jade", None),
    ("color", "table-text", lambda r, t: r.lower() == "#00ff00"),
    ("slot", "table-bg", lambda r, t: r == "image/system/backdrop/default.jpg"),
    ("pack", "demo-jade", None),
]
FIRST_TURN = 6


def symlink_farm(source, target, skip=()):
    os.makedirs(target, exist_ok=True)
    for name in os.listdir(source):
        if name in skip:
            continue
        os.symlink(os.path.join(source, name), os.path.join(target, name))


def build_probe_tree(repo, tree):
    if os.path.lexists(tree):
        shutil.rmtree(tree)
    symlink_farm(repo, tree, skip={"lua", "extensions", "packages", ".git", "build", "builds", "artifacts"})
    # The package catalog refuses a symlinked packages/ directory.
    if os.path.isdir(os.path.join(repo, "packages")):
        shutil.copytree(os.path.join(repo, "packages"), os.path.join(tree, "packages"), symlinks=True)
    symlink_farm(os.path.join(repo, "lua"), os.path.join(tree, "lua"), skip={"config.lua"})
    symlink_farm(os.path.join(repo, "extensions"), os.path.join(tree, "extensions"))

    with open(os.path.join(repo, "lua", "config.lua"), encoding="utf-8") as f:
        config = f.read()
    start = config.index("extension_names = {")
    end = config.index("\n\t},", start)
    body = config[start:end].rstrip()
    if not body.endswith(","):
        body += ","
    config = config[:start] + body + '\n\t\t"%s",' % PROBE_SCRIPT + config[end:]
    with open(os.path.join(tree, "lua", "config.lua"), "w", encoding="utf-8") as f:
        f.write(config)
    with open(os.path.join(tree, PROBE_SCRIPT), "w", encoding="utf-8") as f:
        f.write(PROBE_LUA)

    # A folder slot only needs the files it changes; the rest fall back to the default art.
    art = os.path.join(tree, "uithemeprobe-art", "magatamas")
    os.makedirs(art)
    for index in range(6):
        shutil.copyfile(os.path.join(repo, "themes", "demo-crimson", "emotion", "peach", "0.png"),
                        os.path.join(art, "%d.png" % index))


def read_stages(client_log):
    stages = []
    with open(client_log, encoding="utf-8", errors="replace") as f:
        for line in f:
            at = line.find(STAGE_MARKER)
            if at < 0:
                continue
            try:
                stages.append(json.loads(line[at + len(STAGE_MARKER):].strip()))
            except ValueError:
                pass
    return stages


def evaluate(stages):
    problems = []
    changes = [s for s in stages if str(s.get("stage", "")).startswith("ui_theme_changed:")]
    for change in changes:
        if change.get("id") == "photo-frame":
            problems.append("the client accepted a path outside the asset root: %r" % change)
    changes = [c for c in changes if c.get("id") != "photo-frame"]
    if len(changes) < FIRST_TURN:
        problems.append("expected at least %d theme changes from the first turn, got %d"
                        % (FIRST_TURN, len(changes)))
    for index, change in enumerate(changes):
        if index >= len(EXPECTED):
            problems.append("unexpected extra theme change %r" % change)
            continue
        kind, ident, check = EXPECTED[index]
        if change.get("kind") != kind or change.get("id") != ident:
            problems.append("change %d: expected %s %s, got %s %s"
                            % (index + 1, kind, ident, change.get("kind"), change.get("id")))
            continue
        right, width = change.get("avatar_frame_right"), change.get("dashboard_width")
        if right is None or width is None or abs(float(right) - float(width)) > 2:
            problems.append("change %d: dashboard avatar frame ends at x=%r, dashboard is %r wide"
                            % (index + 1, right, width))
        if check and not check(str(change.get("resolved", "")), change):
            problems.append("change %d (%s %s) resolved to %r"
                            % (index + 1, kind, ident, change.get("resolved")))
    return changes, problems


def main():
    parser = argparse.ArgumentParser(description=__doc__,
                                     formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument("--exe-root", default=".")
    parser.add_argument("--server-exe", help="default: whatever gui_network_smoke.py finds")
    parser.add_argument("--client-exe", help="default: whatever gui_network_smoke.py finds")
    parser.add_argument("--artifact-dir", default="artifacts/ui-theme-runtime")
    parser.add_argument("--mode", default="02p")
    parser.add_argument("--seed", default="20261007")
    parser.add_argument("--platform", default="xcb")
    parser.add_argument("--no-xvfb", action="store_true")
    parser.add_argument("--process-timeout", default="900")
    args = parser.parse_args()

    repo = os.path.abspath(args.exe_root)
    artifacts = os.path.abspath(args.artifact_dir)
    os.makedirs(artifacts, exist_ok=True)
    tree = os.path.join(artifacts, "probe-tree")
    build_probe_tree(repo, tree)

    label = "ui-theme-%s-%s" % (args.mode, args.seed)
    command = [sys.executable, os.path.join(HERE, "gui_network_smoke.py"),
               "--exe-root", repo, "--workdir", tree,
               "--mode", args.mode, "--seed", args.seed,
               "--artifact-dir", artifacts, "--label", label,
               "--platform", args.platform, "--process-timeout", args.process_timeout,
               "--known-base-defect", "server-teardown-crash"]
    if args.no_xvfb:
        command.append("--no-xvfb")
    for flag, value in (("--server-exe", args.server_exe), ("--client-exe", args.client_exe)):
        if value:
            command += [flag, os.path.abspath(value)]
    for name in os.listdir(artifacts):
        if "-ui-theme-" in name and name.endswith(".png"):
            os.remove(os.path.join(artifacts, name))
    env = dict(os.environ, QSAN_ASSET_ROOT=tree)
    smoke = subprocess.run(command, env=env)

    client_log = os.path.join(artifacts, "network-ui-smoke-%s-client.log" % label)
    problems = []
    changes = []
    if smoke.returncode != 0:
        problems.append("gui_network_smoke.py exited %d" % smoke.returncode)
    if not os.path.isfile(client_log):
        problems.append("no client log at %s" % client_log)
    else:
        changes, found = evaluate(read_stages(client_log))
        problems += found
    screenshots = sorted(n for n in os.listdir(artifacts) if "-ui-theme-" in n and n.endswith(".png"))

    summary = {
        "mode": args.mode, "seed": args.seed, "ok": not problems,
        "theme_changes": changes, "screenshots": screenshots, "problems": problems,
    }
    with open(os.path.join(artifacts, label + "-ui-theme-summary.json"), "w", encoding="utf-8") as f:
        json.dump(summary, f, ensure_ascii=False, indent=2)
    print("\ntheme changes seen: %d, screenshots: %d" % (len(changes), len(screenshots)))
    for change in changes:
        print("  %s %s -> %s" % (change.get("kind"), change.get("id"), change.get("resolved", "")))
    if problems:
        print("\nUI theme runtime smoke FAILED:", file=sys.stderr)
        for problem in problems:
            print("  - %s" % problem, file=sys.stderr)
        return 1
    print("UI theme runtime smoke PASSED")
    return 0


if __name__ == "__main__":
    sys.exit(main())
