set(QSAN_SOURCES
    src/main.cpp
    src/client/aux-skills.cpp
    src/client/client.cpp
    src/client/clientplayer.cpp
    src/client/clientstruct.cpp
    src/core/banpair.cpp
    src/core/card.cpp
    src/core/engine.cpp
    src/core/filehandler.cpp
    src/core/general.cpp
    src/core/json.cpp
    src/core/lua-wrapper.cpp
    src/core/oracle_helper.cpp
    src/core/player.cpp
    src/core/protocol.cpp
    src/core/record-analysis.cpp
    src/core/room-state.cpp
    src/core/settings.cpp
    src/core/skill.cpp
    src/core/skill-instance-utils.cpp
    src/core/structs.cpp
    src/core/util.cpp
    src/core/wrapped-card.cpp
    src/dialog/banipdialog.cpp
    src/dialog/cardeditor.cpp
    src/dialog/cardoverview.cpp
    src/dialog/choosegeneraldialog.cpp
    src/dialog/configdialog.cpp
    src/dialog/connectiondialog.cpp
    src/dialog/customassigndialog.cpp
    src/dialog/dialogslsettings.cpp
    src/dialog/distanceviewdialog.cpp
    src/dialog/generaloverview.cpp
    src/dialog/mainwindow.cpp
    src/dialog/mainwindowserverlist.cpp
    src/dialog/maxcardsviewdialog.cpp
    src/dialog/roleassigndialog.cpp
    src/dialog/scenario-overview.cpp
    src/package/assassins.cpp
    src/package/bgm.cpp
    src/package/boss.cpp
    src/package/doudizhu.cpp
    src/package/exclusive-cards.cpp
    src/package/exppattern.cpp
    src/package/fire.cpp
    src/package/godlailailai.cpp
    src/package/happy2v2.cpp
    src/package/hegemony.cpp
    src/package/h-formation.cpp
    src/package/h-momentum.cpp
    src/package/jiange-defense.cpp
    src/package/joy.cpp
    src/package/lei.cpp
    src/package/ling.cpp
    src/package/maneuvering.cpp
    src/package/maotu.cpp
    src/package/meleemode.cpp
    src/package/mobile.cpp
    src/package/mobilemougong.cpp
    src/package/mobileshiji.cpp
    src/package/mobile-strengthen.cpp
    src/package/mountain.cpp
    src/package/ol.cpp
    src/package/ol-strengthen.cpp
    src/package/olwenwu.cpp
    src/package/package.cpp
    src/package/sp.cpp
    src/package/special1v1.cpp
    src/package/special3v3.cpp
    src/package/standard.cpp
    src/package/standard-cards.cpp
    src/package/standard-generals.cpp
    src/package/tenyear.cpp
    src/package/tenyear2.cpp
    src/package/tenyear-strengthen.cpp
    src/package/thicket.cpp
    src/package/tw.cpp
    src/package/wind.cpp
    src/package/wisdom.cpp
    src/package/yczh2016.cpp
    src/package/yczh2017.cpp
    src/package/yin.cpp
    src/package/yingbian.cpp
    src/package/yinhu.cpp
    src/package/yitian.cpp
    src/package/yjcm.cpp
    src/package/yjcm2012.cpp
    src/package/yjcm2013.cpp
    src/package/yjcm2014.cpp
    src/package/yjcm2015.cpp
    src/package/yjcm2022.cpp
    src/package/yjcm2023.cpp
    src/package/zombine.cpp
    src/scenario/boss-mode-scenario.cpp
    src/scenario/challengedeveloper-scenario.cpp
    src/scenario/couple-scenario.cpp
    src/scenario/fancheng-scenario.cpp
    src/scenario/guandu-scenario.cpp
    src/scenario/miniscenarios.cpp
    src/scenario/scenario.cpp
    src/scenario/scenerule.cpp
    src/scenario/zombie-scenario.cpp
    src/server/ai.cpp
    src/server/basicai.cpp
    src/server/gamerule.cpp
    src/server/generalselector.cpp
    src/server/qtupnpportmapping.cpp
    src/server/room.cpp
    src/server/roomthread.cpp
    src/server/roomthread1v1.cpp
    src/server/roomthread3v3.cpp
    src/server/roomthreadxmode.cpp
    src/server/server.cpp
    src/server/serverplayer.cpp
    src/spine/Animation.cpp
    src/spine/AnimationState.cpp
    src/spine/AnimationStateData.cpp
    src/spine/Atlas.cpp
    src/spine/Bone.cpp
    src/spine/IkConstraint.cpp
    src/spine/MeshAttachment.cpp
    src/spine/RegionAttachment.cpp
    src/spine/Skeleton.cpp
    src/spine/SkeletonBinary.cpp
    src/spine/SkeletonClipping.cpp
    src/spine/SkeletonData.cpp
    src/spine/Skin.cpp
    src/spine/Slot.cpp
    src/spine/TransformConstraint.cpp
    src/ui/bubblechatbox.cpp
    src/ui/button.cpp
    src/ui/cardcontainer.cpp
    src/ui/carditem.cpp
    src/ui/CharacterSpineActionController.cpp
    src/ui/chatwidget.cpp
    src/ui/choosetriggerorderbox.cpp
    src/ui/clientlogbox.cpp
    src/ui/dashboard.cpp
    src/ui/easytextpanel.cpp
    src/ui/EmbeddedQmlLoader.cpp
    src/ui/emotionpanel.cpp
    src/ui/generic-cardcontainer-ui.cpp
    src/ui/gifchatbox.cpp
    src/ui/giftitem.cpp
    src/ui/graphicsbox.cpp
    src/ui/graphicspixmaphoveritem.cpp
    src/ui/indicatoritem.cpp
    src/ui/magatamas-item.cpp
    src/ui/photo.cpp
    src/ui/pixmapanimation.cpp
    src/ui/playercardbox.cpp
    src/ui/qsanbutton.cpp
    src/ui/qsan-selectable-item.cpp
    src/ui/replay-timeline.cpp
    src/ui/rolecombobox.cpp
    src/ui/roomscene.cpp
    src/ui/skin-bank.cpp
    src/ui/SpineAnimationManager.cpp
    src/ui/SpineEffectWidget.cpp
    src/ui/SpineGlItem.cpp
    src/ui/SpineIndicatorLine.cpp
    src/ui/sprite.cpp
    src/ui/startscene.cpp
    src/ui/table-pile.cpp
    src/ui/timed-progressbar.cpp
    src/ui/ui-utils.cpp
    src/ui/window.cpp
    src/util/detector.cpp
    src/util/game-snapshot.cpp
    src/util/nativesocket.cpp
    src/util/recorder.cpp
    src/util/replay-game-state.cpp
    src/util/replay-index.cpp
    src/util/replay-takeover.cpp
    swig/sanguosha_wrap.cxx
)

set(QSAN_LUA_SOURCES
    src/lua/lapi.c
    src/lua/lauxlib.c
    src/lua/lbaselib.c
    src/lua/lbitlib.c
    src/lua/lcode.c
    src/lua/lcorolib.c
    src/lua/lctype.c
    src/lua/ldblib.c
    src/lua/ldebug.c
    src/lua/ldo.c
    src/lua/ldump.c
    src/lua/lfunc.c
    src/lua/lgc.c
    src/lua/linit.c
    src/lua/liolib.c
    src/lua/llex.c
    src/lua/lmathlib.c
    src/lua/lmem.c
    src/lua/loadlib.c
    src/lua/lobject.c
    src/lua/lopcodes.c
    src/lua/loslib.c
    src/lua/lparser.c
    src/lua/lstate.c
    src/lua/lstring.c
    src/lua/lstrlib.c
    src/lua/ltable.c
    src/lua/ltablib.c
    src/lua/ltm.c
    src/lua/lundump.c
    src/lua/lvm.c
    src/lua/lzio.c
)

# Headers containing Q_OBJECT must be target sources so CMake AUTOMOC sees them.
set(QSAN_MOC_HEADERS
    src/client/aux-skills.h
    src/client/client.h
    src/client/clientplayer.h
    src/client/clientstruct.h
    src/core/card.h
    src/core/engine.h
    src/core/filehandler.h
    src/core/general.h
    src/core/lua-wrapper.h
    src/core/player.h
    src/core/record-analysis.h
    src/core/settings.h
    src/core/skill.h
    src/core/wrapped-card.h
    src/dialog/banipdialog.h
    src/dialog/cardeditor.h
    src/dialog/cardoverview.h
    src/dialog/choosegeneraldialog.h
    src/dialog/configdialog.h
    src/dialog/connectiondialog.h
    src/dialog/customassigndialog.h
    src/dialog/dialogslsettings.h
    src/dialog/distanceviewdialog.h
    src/dialog/generaloverview.h
    src/dialog/mainwindow.h
    src/dialog/mainwindowserverlist.h
    src/dialog/maxcardsviewdialog.h
    src/dialog/roleassigndialog.h
    src/dialog/scenario-overview.h
    src/package/assassins.h
    src/package/bgm.h
    src/package/boss.h
    src/package/doudizhu.h
    src/package/exclusive-cards.h
    src/package/fire.h
    src/package/godlailailai.h
    src/package/happy2v2.h
    src/package/hegemony.h
    src/package/h-formation.h
    src/package/h-momentum.h
    src/package/jiange-defense.h
    src/package/joy.h
    src/package/lei.h
    src/package/ling.h
    src/package/maneuvering.h
    src/package/maotu.h
    src/package/meleemode.h
    src/package/mobile.h
    src/package/mobilemougong.h
    src/package/mobileshiji.h
    src/package/mobile-strengthen.h
    src/package/mountain.h
    src/package/ol.h
    src/package/ol-strengthen.h
    src/package/olwenwu.h
    src/package/package.h
    src/package/sp.h
    src/package/special1v1.h
    src/package/special3v3.h
    src/package/standard.h
    src/package/standard-cards.h
    src/package/standard-generals.h
    src/package/tenyear.h
    src/package/tenyear-strengthen.h
    src/package/thicket.h
    src/package/tw.h
    src/package/wind.h
    src/package/wisdom.h
    src/package/yczh2016.h
    src/package/yczh2017.h
    src/package/yin.h
    src/package/yingbian.h
    src/package/yinhu.h
    src/package/yitian.h
    src/package/yjcm.h
    src/package/yjcm2012.h
    src/package/yjcm2013.h
    src/package/yjcm2014.h
    src/package/yjcm2015.h
    src/package/yjcm2022.h
    src/package/yjcm2023.h
    src/package/zombine.h
    src/scenario/boss-mode-scenario.h
    src/scenario/challengedeveloper-scenario.h
    src/scenario/couple-scenario.h
    src/scenario/fancheng-scenario.h
    src/scenario/guandu-scenario.h
    src/scenario/miniscenarios.h
    src/scenario/scenario.h
    src/scenario/zombie-scenario.h
    src/server/ai.h
    src/server/basicai.h
    src/server/gamerule.h
    src/server/generalselector.h
    src/server/qtupnpportmapping.h
    src/server/room.h
    src/server/roomthread.h
    src/server/roomthread1v1.h
    src/server/roomthread3v3.h
    src/server/roomthreadxmode.h
    src/server/server.h
    src/server/serverplayer.h
    src/ui/bubblechatbox.h
    src/ui/button.h
    src/ui/cardcontainer.h
    src/ui/carditem.h
    src/ui/CharacterSpineActionController.h
    src/ui/chatwidget.h
    src/ui/choosetriggerorderbox.h
    src/ui/clientlogbox.h
    src/ui/dashboard.h
    src/ui/easytextpanel.h
    src/ui/EmbeddedQmlLoader.h
    src/ui/emotionpanel.h
    src/ui/generic-cardcontainer-ui.h
    src/ui/gifchatbox.h
    src/ui/giftitem.h
    src/ui/graphicsbox.h
    src/ui/graphicspixmaphoveritem.h
    src/ui/indicatoritem.h
    src/ui/magatamas-item.h
    src/ui/photo.h
    src/ui/pixmapanimation.h
    src/ui/playercardbox.h
    src/ui/qsanbutton.h
    src/ui/qsan-selectable-item.h
    src/ui/replay-timeline.h
    src/ui/rolecombobox.h
    src/ui/roomscene.h
    src/ui/skin-bank.h
    src/ui/SpineAnimationManager.h
    src/ui/SpineEffectWidget.h
    src/ui/SpineGlItem.h
    src/ui/SpineIndicatorLine.h
    src/ui/sprite.h
    src/ui/startscene.h
    src/ui/table-pile.h
    src/ui/timed-progressbar.h
    src/ui/window.h
    src/util/detector.h
    src/util/game-snapshot.h
    src/util/nativesocket.h
    src/util/recorder.h
    src/util/replay-game-state.h
    src/util/replay-index.h
    src/util/replay-takeover.h
    src/util/socket.h
)

set(QSAN_FORMS
    src/dialog/cardoverview.ui
    src/dialog/configdialog.ui
    src/dialog/connectiondialog.ui
    src/dialog/dialogslsettings.ui
    src/dialog/generaloverview.ui
    src/dialog/mainwindow.ui
    src/dialog/mainwindowserverlist.ui
)

set(QSAN_BREAKPAD_SOURCES
    src/breakpad/client/windows/crash_generation/client_info.cc
    src/breakpad/client/windows/crash_generation/crash_generation_client.cc
    src/breakpad/client/windows/crash_generation/crash_generation_server.cc
    src/breakpad/client/windows/crash_generation/minidump_generator.cc
    src/breakpad/client/windows/handler/exception_handler.cc
    src/breakpad/common/windows/guid_string.cc
)
